ClassMateZ/urls.py
from django.conf.urls import url
from django.contrib import admin
from app import views
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^app/', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.conf.urls import url
from app import views



app_name = 'app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'week/$', views.index_week, name='index_week'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'about/$', views.about, name='about'),
    url(r'profile/$', views.profile, name='profile'),
    url(r'SquadZ/$', views.SquadZ, name='SquadZ'),
    url(r'^class/(?P<classId>[\w\-]+)/$', views.showClass, name='showClass'),
]

app/models.py
from __future__ import unicode_literals
#from django.template.defaultfilters import slugify
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class Layout(models.Model):
    layoutName = models.CharField(max_length=100, default='New Layout', blank=False)
    zoneCoords = models.CharField(max_length=1000, default='', blank=False)
    image = models.ImageField(upload_to='layout_images')
    def __str__(self):
		return self.layoutName


class Place(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    address = models.CharField(max_length=100);
    layout = models.ForeignKey(Layout, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    def __unicode__(self):
        return self.name


class Class(models.Model):
    name = models.CharField(max_length=100)
    DAY = (
        ('mon', 'Monday'),
        ('tue', 'Tuesday'),
        ('wed', 'Wednesday'),
        ('thu', 'Thursday'),
        ('fri', 'Friday'),
        ('sat', 'Saturday'),
        ('sun', 'Sunday'),
    )
    day = models.CharField(
        max_length=3,
        choices=DAY,
        default='mon',
        blank=False,
    )
    time = models.TimeField(default=datetime.strptime('00', '%H'), blank=False)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)

    classId = models.CharField(max_length=128, unique=True)

    def __str__(self):
		return self.name + " " + str(self.time) + " " + self.day
	#def __unicode__(self):
		#return self.name

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

	name = models.CharField(max_length=100, default='new user', blank=True)
	picture = models.ImageField(upload_to='profile_images', default='./default-user.png', blank=True)
	classes = models.ManyToManyField(Class, blank=True)

	def url_fix(self):
	    url = self.picture.url
	    if url.startswith("/media/media/"):
	        return self.picture.url[22:]
	    else:
	        return self.picture.url

	def __str__(self):
		return self.name

	def __unicode__(self):
		return self.name

class Zone(models.Model):

    users = models.ManyToManyField(UserProfile, blank=True)
    zoneNumber = models.IntegerField(default=0)
    zClass = models.ForeignKey(Class, on_delete=models.CASCADE)
    def __str__(self):
		return "Zone: " + str(self.zoneNumber) + " " + str(self.zClass)

	#def __unicode__(self):
		#return (self.class_id + ", " + self.layout)

ClassMateZ/forms.py
from django import forms
from django.contrib.auth.models import User
from ClassMateZ.models import UserProfile


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ('username', 'email', 'password')
class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('website', 'picture')

ClassMateZ/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

from ClassMateZ.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime

def index(request):
	# Construct a dictionary to pass to the template engine as its context.
	# Note the key boldmessage is the same as {{ boldmessage }} in the template!
	context_dict = {}

	# Obtain our Response object early so we can add cookie information.
	#visitor_cookie_handler(request)

	#context_dict['visits'] = request.session['visits']

	response = render(request, 'ClassMateZ/index.html', context_dict)
	# Call function to handle the cookies
	# Return response back to the user, updating any cookies that need changed.
	return response



def register(request):
	# A boolean value for telling the template
	# whether the registration was successful.
	# Set to False initially. Code changes value to
	# True when registration succeeds.
	registered = False
	# If it's a HTTP POST, we're interested in processing form data.
	if request.method == 'POST':
		# Attempt to grab information from the raw form information.
		# Note that we make use of both UserForm and UserProfileForm.
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)
		# If the two forms are valid...
		if user_form.is_valid() and profile_form.is_valid():
			# Save the user's form data to the database.
			user = user_form.save()
			# Now we hash the password with the set_password method.
			# Once hashed, we can update the user object.
			user.set_password(user.password)
			user.save()
			# Now sort out the UserProfile instance.
			# Since we need to set the user attribute ourselves,
			# we set commit=False. This delays saving the model
			# until we're ready to avoid integrity problems.
			profile = profile_form.save(commit=False)
			profile.user = user
			# Did the user provide a profile picture?
			# If so, we need to get it from the input form and
			#put it in the UserProfile model.
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']
			# Now we save the UserProfile model instance.
			profile.save()
			# Update our variable to indicate that the template
			# registration was successful.
			registered = True
		else:
			# Invalid form or forms - mistakes or something else?
			# Print problems to the terminal.
			print(user_form.errors, profile_form.errors)
	else:
		# Not a HTTP POST, so we render our form using two ModelForm instances.
		# These forms will be blank, ready for user input.
		user_form = UserForm()
		profile_form = UserProfileForm()
		# Render the template depending on the context.
	return render(request,
		'ClassMateZ/register.html',
		{'user_form': user_form,
		'profile_form': profile_form,
		'registered': registered})


def user_login(request):
	# If the request is a HTTP POST, try to pull out the relevant information.
	if request.method == 'POST':
		# Gather the username and password provided by the user.
		# This information is obtained from the login form.
		# We use request.POST.get('<variable>') as opposed
		# to request.POST['<variable>'], because the
		# request.POST.get('<variable>') returns None if the
		# value does not exist, while request.POST['<variable>']
		# will raise a KeyError exception.
		username = request.POST.get('username')
		password = request.POST.get('password')

		# Use Django's machinery to attempt to see if the username/password
		# combination is valid - a User object is returned if it is.
		user = authenticate(username=username, password=password)

		# If we have a User object, the details are correct.
		# If None (Python's way of representing the absence of a value), no user
		# with matching credentials was found.
		if user:
			# Is the account active? It could have been disabled.
			if user.is_active:
				# If the account is valid and active, we can log the user in.
				# We'll send the user back to the homepage.
				login(request, user)
				return HttpResponseRedirect(reverse('index'))
			else:
				# An inactive account was used - no logging in!
				return HttpResponse("Your Rango account is disabled.")
		else:
			# Bad login details were provided. So we can't log the user in.
			print("Invalid login details: {0}, {1}".format(username, password))
			return HttpResponse("Invalid login details supplied.")
	# The request is not a HTTP POST, so display the login form.
	# This scenario would most likely be a HTTP GET.
	else:
		# No context variables to pass to the template system, hence the
		# blank dictionary object...
		return render(request, 'ClassMateZ/login.html', {})


@login_required
def restricted(request):
	return HttpResponse("Since you're logged in, you can see this text!")


@login_required
def user_logout(request):
	# Since we know the user is logged in, we can now just log them out.
	logout(request)
	# Take the user back to the homepage.

	return HttpResponseRedirect(reverse('index'))

def get_server_side_cookie(request, cookie, default_val=None):
	val = request.session.get(cookie)
	if not val:
		val = default_val
	return val

def visitor_cookie_handler(request):
	visits = int(get_server_side_cookie(request, 'visits', '1'))
	last_visit_cookie = get_server_side_cookie(request,
	'last_visit',
	str(datetime.now()))
	last_visit_time = datetime.strptime(last_visit_cookie[:-7],
	'%Y-%m-%d %H:%M:%S')
	# If it's been more than a day since the last visit...
	if (datetime.now() - last_visit_time).days > 0:
		visits = visits + 1
		#update the last visit cookie now that we have updated the count
		request.session['last_visit'] = str(datetime.now())
	else:
		visits = 1
		# set the last visit cookie
		request.session['last_visit'] = last_visit_cookie
	# Update/set the visits cookie
	request.session['visits'] = visits

templates/ClassMateZ/SquadZ.html
<!--SquadZ.html to view SquadZ page -->
<!DOCTYPE html>
{% extends 'ClassMateZ/base.html' %}
{% load staticfiles %}

<html class="test">
    <head>
        <title>
            {% block title_block %}
                SquadZ
            {% endblock %}
        </title>

    <body>
        {% block body_block %}
            <h1>SquadZ</h1>
            <img class="classmatez" src="{{ MEDIA_URL }}coming_soon.gif" style="margin:auto; width:100%; padding:10px; padding-bottom:35px; border-radius: 15px; " />
        {% endblock %}
    </body>


</html>

templates/ClassMateZ/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>

        <!-- title of the base -->
        <title>
            {% block title_block %}
            ClassMateZ base
            {% endblock %}
        </title>

        <!-- stylesheet and Js links -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">



    </head>
    <body>

        <!-- Navigation Bar start -->
        <div class="container" >

        <nav class="navbar navbar-inverse">
  <div class="container-fluid" >
    <div class="navbar-header" >

      <a class="navbar-brand" href="/#">ClassMateZ</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">

        <!-- href of Home in the Navigation Bar -->
        <li class="active"><a href="/#">Home</a></li>

        <!-- href of About in the Navigation Bar -->
        <li><a href="{% url 'app:about' %}">About</a></li>

        <!-- authenticated if the user login he will be able to see the profile and SquadZ his name and the Log Out  -->
        {% if user.is_authenticated %}
        <li><a href="{% url 'app:profile' %}">My Account</a></li>
        <li><a href="{% url 'app:SquadZ' %}">SquadZ</a></li>
        {% endif %}
      </ul>

      <!-- Navigation Bar right section the login(drop down) and the Singup link -->
      <ul class="nav navbar-nav navbar-right">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><p class="navbar-text">Welcome {{ user.username }}!</p></li>
        <li><a href="{% url 'app:logout' %}">Logout</a></li>
        {% else %}

        <li><p class="navbar-text">Already have an account?</p></li>
        <li><a href="/app/register">Sign Up </a></li>

        <!-- the form of the drop login -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
			<ul id="login-dp" class="dropdown-menu">
				<li>
				 <div class="row">
						<div class="col-md-12">


							 <form class="form" role="form" method="post" action="{% url 'app:login' %}" accept-charset="UTF-8" id="login-nav">
							     {% csrf_token %}
									<div class="form-group">
										 <label class="sr-only" for="exampleInputEmail2">Email address</label>
										 <input type="text" name="username" class="form-control" id="namespace" placeholder="example name" required>
									</div>
									<div class="form-group">
										 <label class="sr-only" for="exampleInputPassword2">Password</label>
										 <input type="password" name="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
                                         <div class="help-block text-right"><a href="">Forgotten your password ?</a></div>
									</div>
									<div class="form-group">
										 <button type="submit" class="btn btn-primary btn-block" value="submit">Sign in</button>
									</div>
									<div class="checkbox">
										 <label>
										 <input type="checkbox"> keep me logged-in
										 </label>
									</div>
							 </form>

						</div>
					</div>
                </li>
            </ul>
        {% endif %}
        </li>
        <!-- the form of the drop login END -->

        </ul>
    </div>
  </div>
</nav>

            <!-- control the boody length -->
            <div class="jumbotron">
                {% block body_block %}
                {% endblock %}
                <div>
                    <br />

                </div>
            </div>
        </div>
    </body>
</html>

templates/ClassMateZ/index.html
<!DOCTYPE html>
{% extends 'ClassMateZ/base.html' %}
{% load staticfiles %}

<html>
    <head>
        <title>
            {% block title_block %}
                Index
            {% endblock %}
        </title>

        <!-- stylesheet, js and jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script>
            jQuery(document).ready(function($) {
                $(".clickable-row").click(function() {
                    window.location = $(this).data("href");
                });
            });
        </script>

    </head>
    <body>
    {% block body_block %}

        <img class="classmatez" src="{{ MEDIA_URL }}ClassmateZ.png" style="margin:auto; width:100%; padding:10px; padding-bottom:35px;" /> <!-- classmatez Icon -->


            <dir style="background-color:white; border-radius: 15px; padding: 2px; "><!-- background boder for the table and the text(Since you aren't signed in, ClassMateZ has limited functionality)  -->

                    {% if user.is_authenticated %}

                <dir>
                        <div style="font-size:36px; text-transform:capitalize;" >Today is {{day}}</div> <!-- show Day -->
                        </br>
                        <a href="{% url 'app:index_week' %}">show this <b>week</b></a> <!-- Link to show the week time table -->

                    <!-- time table start section -->
                    <dir class="table-responsive">
                        <table class="table">
                            <thead>
                              <tr>
                                <th>Class</th>
                                <th>Time</th>
                                <th>Place</th>
                              </tr>
                            </thead>
                            <tbody>
                                {% for class in userClasses.classes.all %}
                                  <tr>
                                    <td>{{ class.name }}</td>
                                    <td>{{ class.time }}</td>
                                    <td>{{ class.place }}</td>
                                    <td><a href = "{% url 'app:showClass' class.classId %}">See Class</a></td>
                                  </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        {% else %}
                        <h3 style="text-align: center;">Since you aren't signed in, ClassMateZ has limited functionality</h3>
                        {% endif %}
                        {% endblock %}
                    </dir>
                    <!-- time table start section END -->

                </dir>
            </dir>


    </body>
</html>

templates/ClassMateZ/index_week.html
<!DOCTYPE html>
{% extends 'ClassMateZ/base.html' %}
{% load staticfiles %}

<html>
    <head>
        <title>
            {% block title_block %}
                Index
            {% endblock %}
        </title>

        <!-- stylesheet, js and jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script>
            jQuery(document).ready(function($) {
                $(".clickable-row").click(function() {
                    window.location = $(this).data("href");
                });
            });
        </script>

    </head>
    <body>
    {% block body_block %}
        <img class="classmatez" src="{{ MEDIA_URL }}ClassmateZ.png" style="margin:auto; width:100%; padding:10px; padding-bottom:35px;" /> <!-- classmatez Icon -->

        {% if user.is_authenticated %}
        <dir style="background-color:white; border-radius: 15px; padding: 2px; "> <!-- background boder for the table and the text(Since you aren't signed in, ClassMateZ has limited functionality)  -->
            <dir>
                <div style="font-size:36px; text-transform:capitalize;" >Today is {{day}}</div> <!-- show Day -->
                </br>
                <a href="{% url 'app:index' %}">show <b>Today</b></a> <!-- Link to show the week time table -->


                <!-- time table start section -->
                <dir class="table-responsive">
                    <table style="" class="table">
                        <thead style="">
                            {% for class in userClasses.classes.all %}
                            <tr>
                                <th>Monday</th>
                                <th>Tuesday</th>
                                <th>Wednesday</th>
                                <th>Thursday</th>
                                <th>Friday</th>
                                <th>Saturday</th>
                                <th>Sunday</th>
                            </tr>
                        </thead>
                        <tbody style="">
                            <tr>
                                <td>1</td>
                                <td>2</td>
                                <td>3</td>
                                <td>4</td>
                                <td>5</td>
                                <td>6</td>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>2</td>
                                <td>3</td>
                                <td>4</td>
                                <td>5</td>
                                <td>6</td>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>2</td>
                                <td>3</td>
                                <td>4</td>
                                <td>5</td>
                                <td>6</td>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>2</td>
                                <td>3</td>
                                <td>4</td>
                                <td>5</td>
                                <td>6</td>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>2</td>
                                <td>3</td>
                                <td>4</td>
                                <td>5</td>
                                <td>6</td>
                                <td>7</td>
                            </tr>
                        </tbody>

                        {% endfor %}
                    </table>

                    {% else %}

                    <h3>Since you aren't signed in, ClassMateZ has limited functionality</h2>

                    {% endif %}
                    {% endblock %}
                </dir>
                <!-- time table start section END -->

            </dir>
        </dir>

    </body>
</html>

templates/ClassMateZ/profile.html
<!DOCTYPE html>
{% extends 'ClassMateZ/base.html' %}
{% load staticfiles %}
<htm>
    <head>

    <title>
            <!-- title profile -->
            {% block title_block %}
                profile
            {% endblock %}
    </title>

        <!-- stylesheet, js and jQuery -->
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />

    </head>
    <body>
    {% block body_block %}
        <h1 style="text-transform:capitalize;">{{ user.username }} Profile</h1><br /> <!-- to show the username for how oun this Profile -->
            {% if user.is_authenticated %}
                {% if updated %}
                    <strong>Profile updated!</strong>
                    <a type="button" class="btn btn-primary" href="{% url 'app:index' %}">Return to the homepage.</a><br />

                {% else %}


                        {% csrf_token %}


                        <div class="container">

                              	<hr>
                              	<form class="form-horizontal" id="profile_form" method="post" action="{% url 'app:profile' %}" enctype="multipart/form-data"><!-- to show and update username -->
                            	<div class="row">
                                  <!-- left column -->
                                  <div class="col-md-3">
                                    <div class="text-center">
                                      <img src= {{user_profile.url_fix}} class="avatar img-circle" alt="avatar" width = 200 height = 200><!-- to show and update profile image -->
                                      <h6>Upload a different photo...</h6>

                                      <input id="file" type="file" name="picture" class="form-control">
                                    </div>
                                  </div>

                                  <!-- edit form column -->
                                  <div class="col-md-9 personal-info">
                                    <div class="alert alert-info alert-dismissable">
                                      <a class="panel-close close" data-dismiss="alert">×</a>
                                      <i class="fa fa-coffee"></i>
                                       make sure to click <strong>Save Changes</strong>. to Update you profile.
                                    </div>
                                    <h3>Personal information</h3>


                                        {% csrf_token %}
                                      <div class="form-group">
                                        <label class="col-lg-3 control-label">Name:</label>
                                        <div class="col-lg-8">
                                          <input class="form-control" name="name" type="text" value="{{ user_profile.name }}"> <!-- to show and update name -->
                                        </div>
                                      </div>

                                      <div class="form-group">
                                        <label class="col-lg-3 control-label">Email:</label>
                                        <div class="col-lg-8">
                                          <input class="form-control" name="email" type="text" value="{{ user.email }}"> <!-- to show and update Email -->
                                        </div>
                                      </div>

                                        <!-- to select Classes -->
                                     <div class="form-group">
                                        <label class="col-lg-3 control-label">Classes:</label>
                                        <div class="col-lg-8">
                                          <div class="ui-select">
                                              <select multiple="multiple" class="form-control" id="id_classes" name="classes">
                                                    {% for class in all_classes %}
                                                        <option style="width:400px;" value="{{ class.name }}">{{ class.name }}</option>
                                                    {% endfor %}
                                            </select>
                                          </div>

                                          <div>
                                            <h5 class="help">Hold down "Control", or "Command" on a Mac, to select more than one.</h5>
                                        </div>


                                      </div>
                                     </div>



                                      <div class="form-group">
                                        <label class="col-md-3 control-label"></label>
                                        <div class="col-md-8">
                                          <button type="submit" class="btn btn-default" value="submit">Save Changes</button><!-- submite changes -->
                                          <input type="reset" class="btn btn-default" value="Cancel">
                                        </div>
                                      </div>

                                    </form>
                                  </div>
                              </div>
                            </div>
                            <hr>



                        </dir>


                    {% endif %}
                {% else %}
                <h2>We are sorry, you don't seem to be signed in</h2>
                {% endif %}

                <!-- fotter -->
                <div style="bottom: 0px;">ClassMateZ have been coded and desinged for Web Application Development 2 (Team Project). University of Glasgow</div>

    {% endblock %}
    </body>



</html>

templates/ClassMateZ/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>

        <!-- stylesheet and Js for improve looking -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/register-log.css' %}">

    </head>


	<body style="padding-top:180px;">
		    <img class="classmatez" src="{{ MEDIA_URL }}ClassmateZ.png" style="display:block; margin:auto; width:55%; padding-bottom:25px; padding-top:125px;" /> <!-- classmatez Icon -->


<div class="container-fluid">
    <section class="container">
		<div class="container-page">
			<div class="col-md-6" style="padding-bottom:30px;">

			    <!-- Description bout the website -->
				<h2>Description</h3>
			    <p>
			        ClassMatez is a web application designed to help students at
                    university connect with their classmates, make friends and
                    meet new people across their courses.
                </p>
				</div>

			</div>

			<!-- the form section to enter the information to registered -->
			<div class="col-md-6">
				 {% if registered %}
                            <strong>thank you for registering!</strong>
                            <a type="button" class="btn btn-primary" href="{% url 'app:index' %}">Return to the homepage.</a><br />
                        {% else %}

        				<form id="user_form" method="post" action="{% url 'app:register' %}" enctype="multipart/form-data">
        				     {% csrf_token %}

            				     <div class="col-lg-12">
                					<label>Username</label>
                					<input type="text" name="username" class="form-control" id="" value="">
                				</div>


                				<div class="col-lg-12">
                					<label>Password</label>
                					<input type="password" name="password" class="form-control" id="" value="">
                				</div>

                				<div class="col-lg-12">
                					<label>Email</label>
                					<input type="email" name="email" class="form-control" id="" value="">
                				</div>

                				<input type="submit" name="register" value="register" style="width:520px; margin:15px;" />
        			        </div>
        			         {% endif %}
        			 </form>
                    <!-- the form section END-->
	</section>
</div>


	</body>
</html>